### ISSUE TITLE
error with parser.py

### ISSUE THREAD

**Issue by Foul-Tarnished** [AsteriskAmpersand/Carian-Archive#5]
Hello, I don't know why this happens, I have the GR folder for engUS and fraFR, fmg are in xml

any idea ? thanks

```
Traceback (most recent call last):
  File "E:\Elden_Ring_modding\fr_extract\parser.py", line 123, in <module>
    text = loadFromChunk(chunk)
  File "E:\Elden_Ring_modding\fr_extract\parser.py", line 93, in loadFromChunk
    npcIds = loadNPCNames(chunk,lang)
  File "E:\Elden_Ring_modding\fr_extract\parser.py", line 16, in loadNPCNames
    npcNames = loadTextFile(path)
  File "E:\Elden_Ring_modding\fr_extract\parser.py", line 50, in loadTextFile
    textElements = root.getchildren()[3].getchildren()
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by Foul-Tarnished** [comment]
Fixed by using Python 3.8
(also pip install markdown)
